Adicionando message collector ao comando play
dev-house-community/EarphoneJack pull request #4
Opened 2021-04-24 14:27 UTC by DevRadhy

Adicionando message collector ao comando play para captura a escolha da música entre 1 e 10.

2021-04-24 18:48 UTC, caio-emidio requested changes
Leves comentarios de coisas q eu acredito q vc pode arrumar :)

2021-04-24 18:48 UTC, caio-emidio commented on src/commands/play.js
> +    const filter = m => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].includes(Number(m.content));
Parece ser mais interessante... Veja se funciona. 

Shortness version.
[...Array(10).keys()]

2021-04-24 18:48 UTC, caio-emidio commented on src/controllers/MusicController.js
> +    const embed = new MessageEmbed()
Rever ";"

 ou ate mesmo colocar um prettier no codigo q ele resolve isso ;)

2021-04-24 18:48 UTC, caio-emidio commented on src/commands/play.js
> +      embed.setColor('#ffd596')
Sem ; no fim da linha

2021-04-27 17:05 UTC, jakeliny approved these changes
Good Job!!

2021-04-27 22:41 UTC, merged